services:
  master:
    build:
      dockerfile: dockerfile_master
      context: .
    ports:
      - "3000:3000"
    depends_on:
      secondary1:
        condition: service_healthy
      secondary2:
        condition: service_healthy

  secondary1:
    build:
      dockerfile: dockerfile_secondary
      context: .
    ports:
      - "3001:3001"
  secondary2:
    build:
      dockerfile: dockerfile_secondary
      context: .
    ports:
      - "3002:3002"
