services:
  master:
    container_name: 'master'
    build:
      dockerfile: dockerfile_master
      context: .
    ports:
      - "3000:8001"
    command: 'python3 master.py --port=8001'

  secondary1:
    container_name: 'secondary1'
    build:
      dockerfile: dockerfile_secondary
      context: .
    command: 'python3 secondary.py --port=8000'

  secondary2:
    container_name: 'secondary2'
    build:
      dockerfile: dockerfile_secondary
      context: .
    command: 'python3 secondary.py --port=8000'

