@startuml
user -> master: msg, concern=2

activate master
master -> secondary1: msg
master -> secondary2: msg
master -> secondary3: msg

'as_completed
master <- secondary3 : ACK
master <- secondary1 : ACK

'2 responses received, concern=2, returning
user  <- master
deactivate master

master <- secondary2 : ACK (lost)
@enduml

