@startuml
user -> master

activate master
master -> secondary1: msg
master -> secondary2: msg
master -> secondary3: msg

'as_completed

master <- secondary3 : 200
master <- secondary1 : 200
master <- secondary2 : 200

user  <- master
deactivate master

@enduml

