@startuml
user -> master: msg, concern=2

activate master
master -> secondary1: msg
master -> secondary2: msg
master -> secondary3: msg

'as_completed

master <- secondary3 : 200
master <- secondary1 : 200

'2 responses received, concern=2, returning
user  <- master
deactivate master

master <- secondary2 : 200 (lost)


@enduml

